config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :events
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords', sessions: 'users/sessions',:omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/about' => 'about#index'
  get '/dashboard' => 'dashboard#index'
  get '/dashboard/set_user_status_to_approved'
  get 'events/:id/add_ta' => 'events#add_ta'
  get 'events/:id/remove_ta' => 'events#remove_ta'
  get 'get_involved' => 'welcome#get_involved'
  root 'welcome#index'
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    @application.user = current_user
    respond_to do |format|
      if @application.save
        @application.user.set_pending # update user status to pending
        #send admin an email notification that there is a new applicant
        AdminMailer.approve_applicant_email(params[:name], params[:email], params[:about_you], params[:how_you_found_us], params[:why_volunteer]).deliver
        format.html { redirect_to dashboard_path, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:name, :email, :about_you, :how_you_found_us, :why_volunteer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(application) do |f| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, required: true, class: 'form-control', value:current_user.email if current_user %>
  </div>

  <div class="field">
    <%= f.label :about_you %>
    <%= f.text_area :about_you, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :how_you_found_us %>
    <%= f.text_area :how_you_found_us, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :why_volunteer %>
    <%= f.text_area :why_volunteer, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application, class: 'btn btn-sm btn-info' %> |
<%= link_to 'Back', applications_path, class: 'btn btn-sm btn-default' %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applications</h1>

<table class="table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>About you</th>
      <th>How you found us</th>
      <th>Why volunteer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.name %></td>
        <td><%= application.email %></td>
        <td><%= application.about_you %></td>
        <td><%= application.how_you_found_us %></td>
        <td><%= application.why_volunteer %></td>
        <td><%= link_to 'Show', application, class: 'btn btn-sm btn-info' %></td>
        <td><%= link_to 'Edit', edit_application_path(application), class: 'btn btn-sm btn-warning' %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path, class: 'btn btn-sm btn-default' %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @application.email %>
</p>

<p>
  <strong>About you:</strong>
  <%= @application.about_you %>
</p>

<p>
  <strong>How you found us:</strong>
  <%= @application.how_you_found_us %>
</p>

<p>
  <strong>Why volunteer:</strong>
  <%= @application.why_volunteer %>
</p>

<%= link_to 'Edit', edit_application_path(@application), class: 'btn btn-sm btn-warning' %> |
<%= link_to 'Back', applications_path, class: 'btn btn-sm btn-default' %>