config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :events
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords', sessions: 'users/sessions',:omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/about' => 'about#index'
  get '/dashboard' => 'dashboard#index'
  get '/dashboard/set_user_status_to_approved'
  get 'events/:id/add_ta' => 'events#add_ta'
  get 'events/:id/remove_ta' => 'events#remove_ta'
  get 'get_involved' => 'welcome#get_involved'
  root 'welcome#index'
end

app/views/layouts/_navbar.html.erb
<!--Begin navbar-->
        <nav class="navbar navbar-default">
          <div class="container-fluid">

            <div class="navbar-header">

              <!-- this is the hamburger menu -->
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gdisdnav" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand nav" href="/">
                <%= image_tag 'gdi-logo.png', alt: 'GDI', class: 'logo' %>
              </a>
            </div>
            <!-- Content for navigation -->
            <div class="collapse navbar-collapse" id="gdisdnav">
              <ul class="nav navbar-nav">

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle text-lowercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About Us<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li class="text-lowercase"><a href="https://www.girldevelopit.com/">Girl Develop It</a></li>
                      <hr class="drop-hr">
                    <li class="text-lowercase"><a href="https://www.girldevelopit.com/about">Our Mission</a></li>
                      <hr class="drop-hr">
                    <li class="text-lowercase"><a href="<%= about_path %>">Meet our team</a></li>
                  </ul>
                </li>
                <li class="text-lowercase"><a href="<%= get_involved_path %>">Get Involved</a></li>
                <% if !current_user.nil? %>
                  <li class="text-lowercase"><a href="<%= dashboard_path %>">Dashboard</a></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle text-lowercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome, <%=current_user.email%><%=current_user.name%><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <!-- <li class="text-lowercase"><#%= link_to "Profile", profile_path %></li> -->
                      <li class="text-lowercase"><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <hr class="drop-hr">
                      <li class="text-lowercase"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
                    </ul>
                  </li>
                <% end %>
                <!-- <#%if !current_user.nil? && current_user.has_role?(:admin)%>
                  <li class="text-lowercase lower-nav"><#%= link_to 'Administration', admin_path%></li>
                <#%end%> -->
                <% if current_user.nil? %>
                  <li class="dropdown">
                    <a href="#" id="meetup-signin" class="dropdown-toggle text-lowercase" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign Up or Sign In<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li class="text-lowercase"><%= link_to "sign up", new_user_registration_path %></li>
                        <hr class="drop-hr">
                      <li class="text-lowercase"><%= link_to "sign in", user_session_path %></li>
                        <hr class="drop-hr">
                      <li class="text-lowercase lower-nav"><%= link_to "sign in with meetup", user_meetup_omniauth_authorize_path %></li>
                    </ul>
                  </li>
                <% end %>
              </ul>
            </div><!--end navigation content -->
          </div><!--end nav container-->
        </nav>
      <!--End navbar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Volunteermanagerapp</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    <!-- add alert and notices for Devise installation -->
      <div id="notice"><%= notice %></div>
  		<%= yield %>
    </div>
  </body>
</html>